site_name: Adémar's recipes

theme:
  name: simple-blog
  icon:
    repo: fontawesome/brands/github
    logo: fontawesome/solid/bowl-rice
  features:
    - navigation.tracking
    #  - navigation.expand
    - navigation.top
    - navigation.footer
    - content.code.copy

nav:
  - Home: index.md
  - African:
      - Bissap: african/bissap.md
  - American: 
      - Pulled Pork: american/pulled-pork.md
  - Asian:
      - Easy Dumplings: asian/potstickers.md
      - Yu Xian Eggplant: asian/eggplants.md
  - Desert:
      - Carrot Cake: desert/carrot-cake.md
      - Cookies: desert/cookies.md
  - Italian:
      - Pizza dough: italian/pizza.md

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.gemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg

extra_css:
  - assets/stylesheets/emoji.css